alias vi='NVIM_APPNAME=nvim-vi nvim'
export EDITOR="nvim"
export SUDO_EDITOR="$EDITOR"

# use ctrl-z to toggle in and out of bg
if [[ $- == *i* ]]; then 
  stty susp undef
  bind '"\C-z":" fg\015"'
fi

# opencode
export PATH=$HOME/.opencode/bin:$PATH
