export EDITOR="nvim"
export SUDO_EDITOR="$EDITOR"

# use ctrl-z to toggle in and out of bg
if [[ $- == *i* ]]; then 
  stty susp undef
  bind '"\C-z":" fg\015"'
fi

# opencode
export PATH=$HOME/.opencode/bin:$PATH

# posting tui
export POSTING_THEME_DIRECTORY=$HOME/.config/posting/themes

alias vi='NVIM_APPNAME=nvim-vi nvim'

alias inspect="NODE_OPTIONS='--inspect'"
alias debug=inspect
